name: 1.ci

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    name: 1.ci
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.OPENOS365_SSH }} 
          known_hosts: 'gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY='
      - name: Check Out Repo 
        uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.OPENOS365_GITHUB_TOKEN }}
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.OPENOS365_DOCKERHUB_USER }}
          password: ${{ secrets.OPENOS365_DOCKERHUB_PASSWORD }}
      - name: Login to qingcloud dockerhub
        uses: docker/login-action@v2
        with:
          registry: dockerhub.qingcloud.com
          username: ${{ secrets.OPENOS365_DOCKERHUB_QINGCLOUD_USER }}
          password: ${{ secrets.OPENOS365_DOCKERHUB_QINGCLOUD_PASSWORD }}
      - name: run 1.ci.caller.sh
        env:
          GITHUB_TOKEN: ${{ secrets.OPENOS365_GITHUB_TOKEN }}
          OPENOS365_SSH: ${{ secrets.OPENOS365_SSH }}
          OPENOS365_DOCKERHUB_USER: ${{ secrets.OPENOS365_DOCKERHUB_USER }}
          OPENOS365_DOCKERHUB_PASSWORD: ${{ secrets.OPENOS365_DOCKERHUB_PASSWORD }}
          OPENOS365_DOCKERHUB_QINGCLOUD_USER: ${{ secrets.OPENOS365_DOCKERHUB_QINGCLOUD_USER }}
          OPENOS365_DOCKERHUB_QINGCLOUD_PASSWORD: ${{ secrets.OPENOS365_DOCKERHUB_QINGCLOUD_PASSWORD }}
          OPENOS365_GITHUB_TOKEN: ${{ secrets.OPENOS365_GITHUB_TOKEN }}
        run: |
          ./1.ci.caller.sh
